### ISSUE TITLE
Create a 0.1 release tag

### ISSUE THREAD

**Issue by dhorgan** [DataDog/sketches-py#3]
Would it be possible to issue a 0.1 release for this package, so that it can be installed by tag reference rather than by commit reference? For example, right now I need to do this:

```
pip install git+https://github.com/DataDog/sketches-py@312f3c681097a96c04564cb314a684cb49a961dc#egg=ddsketch
```

But it would be really nice (and less verbose) if I could do this instead:

```
pip install git+https://github.com/DataDog/sketches-py@0.1#egg=ddsketch
```

**Comment by githomin** [comment]
Sorry for the long delay. We released the paper version with the various bug fixes from Sep 2019 as v0.1, and the current version as v1.0.
