### ISSUE TITLE
second_key triggered an exception "list index out of range" in store.py #185

### ISSUE THREAD

**Issue by hay86** [DataDog/sketches-py#57]
Because if second_key=0, it will use key instead which will lead to wrong value of new_max_key

 def _extend_range(self, key, second_key=None):
        # type: (int, Optional[int]) -> None
        """Grow the bins as necessary and call _adjust"""
        second_key = second_key or key
        new_min_key = min(key, second_key, self.min_key)
        new_max_key = max(key, second_key, self.max_key)

**Comment by Kyle-Verhoog** [comment]
@hay86 thanks for reporting! I opened up #58 to resolve the issue.

Do you have the code that you used to create the issue? I tried to quickly reproduce it but wasn't able to.

**Comment by hay86** [comment]
Yeah, the store size is a little bit big, here I attached as follows if you want to use them for reproducing the crash. @Kyle-Verhoog 

store #1
store: {-386: 0.0, -385: 0.0, -384: 0.0, -383: 1.0, -382: 0.0, -381: 0.0, -380: 0.0, -379: 0.0, -378: 0.0, -377: 0.0, -376: 0.0, -375: 0.0, -374: 0.0, -373: 0.0, -372: 0.0, -371: 0.0, -370: 0.0, -369: 0.0, -368: 0.0, -367: 0.0, -366: 0.0, -365: 0.0, -364: 0.0, -363: 0.0, -362: 0.0, -361: 0.0, -360: 0.0, -359: 0.0, -358: 0.0, -357: 0.0, -356: 1.0, -355: 0.0, -354: 1.0, -353: 0.0, -352: 0.0, -351: 0.0, -350: 1.0, -349: 0.0, -348: 0.0, -347: 0.0, -346: 0.0, -345: 1.0, -344: 0.0, -343: 0.0, -342: 1.0, -341: 0.0, -340: 0.0, -339: 0.0, -338: 0.0, -337: 0.0, -336: 1.0, -335: 0.0, -334: 1.0, -333: 1.0, -332: 1.0, -331: 0.0, -330: 1.0, -329: 0.0, -328: 0.0, -327: 0.0, -326: 0.0, -325: 0.0, -324: 1.0, -323: 1.0, -322: 1.0, -321: 1.0, -320: 0.0, -319: 1.0, -318: 1.0, -317: 0.0, -316: 1.0, -315: 0.0, -314: 2.0, -313: 2.0, -312: 1.0, -311: 1.0, -310: 2.0, -309: 1.0, -308: 0.0, -307: 0.0, -306: 0.0, -305: 5.0, -304: 5.0, -303: 2.0, -302: 2.0, -301: 0.0, -300: 1.0, -299: 1.0, -298: 4.0, -297: 2.0, -296: 5.0, -295: 4.0, -294: 2.0, -293: 2.0, -292: 0.0, -291: 5.0, -290: 4.0, -289: 3.0, -288: 8.0, -287: 3.0, -286: 1.0, -285: 8.0, -284: 4.0, -283: 7.0, -282: 5.0, -281: 3.0, -280: 5.0, -279: 12.0, -278: 9.0, -277: 11.0, -276: 12.0, -275: 12.0, -274: 7.0, -273: 9.0, -272: 11.0, -271: 11.0, -270: 15.0, -269: 10.0, -268: 10.0, -267: 11.0, -266: 11.0, -265: 15.0, -264: 13.0, -263: 8.0, -262: 17.0, -261: 13.0, -260: 11.0, -259: 26.0, -258: 19.0, -257: 20.0, -256: 22.0, -255: 23.0, -254: 15.0, -253: 18.0, -252: 29.0, -251: 24.0, -250: 23.0, -249: 21.0, -248: 22.0, -247: 35.0, -246: 24.0, -245: 27.0, -244: 41.0, -243: 26.0, -242: 44.0, -241: 36.0, -240: 35.0, -239: 42.0, -238: 40.0, -237: 50.0, -236: 38.0, -235: 52.0, -234: 53.0, -233: 61.0, -232: 54.0, -231: 46.0, -230: 62.0, -229: 49.0, -228: 56.0, -227: 73.0, -226: 53.0, -225: 54.0, -224: 75.0, -223: 65.0, -222: 80.0, -221: 53.0, -220: 86.0, -219: 76.0, -218: 90.0, -217: 96.0, -216: 85.0, -215: 94.0, -214: 112.0, -213: 141.0, -212: 109.0, -211: 87.0, -210: 118.0, -209: 112.0, -208: 112.0, -207: 138.0, -206: 123.0, -205: 160.0, -204: 142.0, -203: 187.0, -202: 143.0, -201: 140.0, -200: 160.0, -199: 178.0, -198: 193.0, -197: 174.0, -196: 168.0, -195: 206.0, -194: 223.0, -193: 227.0, -192: 218.0, -191: 265.0, -190: 260.0, -189: 289.0, -188: 293.0, -187: 241.0, -186: 308.0, -185: 308.0, -184: 319.0, -183: 315.0, -182: 276.0, -181: 348.0, -180: 363.0, -179: 386.0, -178: 365.0, -177: 420.0, -176: 398.0, -175: 400.0, -174: 449.0, -173: 416.0, -172: 444.0, -171: 468.0, -170: 489.0, -169: 460.0, -168: 484.0, -167: 532.0, -166: 531.0, -165: 514.0, -164: 599.0, -163: 539.0, -162: 660.0, -161: 555.0, -160: 694.0, -159: 634.0, -158: 738.0, -157: 749.0, -156: 787.0, -155: 733.0, -154: 826.0, -153: 875.0, -152: 876.0, -151: 881.0, -150: 816.0, -149: 972.0, -148: 915.0, -147: 984.0, -146: 1001.0, -145: 1012.0, -144: 1049.0, -143: 1048.0, -142: 1015.0, -141: 1072.0, -140: 1160.0, -139: 1211.0, -138: 1300.0, -137: 1321.0, -136: 1294.0, -135: 1370.0, -134: 1324.0, -133: 1441.0, -132: 1318.0, -131: 1580.0, -130: 1495.0, -129: 1433.0, -128: 1606.0, -127: 1575.0, -126: 1595.0, -125: 1623.0, -124: 1761.0, -123: 1631.0, -122: 1830.0, -121: 1717.0, -120: 1672.0, -119: 1902.0, -118: 1885.0, -117: 1918.0, -116: 1910.0, -115: 2036.0, -114: 1867.0, -113: 1913.0, -112: 1997.0, -111: 1973.0, -110: 1929.0, -109: 2125.0, -108: 1962.0, -107: 1938.0, -106: 2143.0, -105: 1965.0, -104: 1900.0, -103: 2284.0, -102: 2122.0, -101: 2023.0, -100: 2083.0, -99: 1989.0, -98: 1965.0, -97: 2113.0, -96: 1917.0, -95: 1949.0, -94: 2006.0, -93: 2029.0, -92: 1950.0, -91: 1865.0, -90: 1881.0, -89: 2029.0, -88: 1789.0, -87: 1813.0, -86: 1832.0, -85: 1795.0, -84: 1643.0, -83: 1534.0, -82: 1579.0, -81: 1526.0, -80: 1633.0, -79: 1383.0, -78: 1420.0, -77: 1376.0, -76: 1289.0, -75: 1317.0, -74: 1209.0, -73: 1233.0, -72: 1139.0, -71: 1020.0, -70: 990.0, -69: 1079.0, -68: 850.0, -67: 840.0, -66: 798.0, -65: 731.0, -64: 677.0, -63: 591.0, -62: 633.0, -61: 566.0, -60: 508.0, -59: 493.0, -58: 417.0, -57: 334.0, -56: 317.0, -55: 294.0, -54: 465.0, -53: 255.0, -52: 241.0, -51: 212.0, -50: 199.0, -49: 200.0, -48: 140.0, -47: 120.0, -46: 104.0, -45: 150.0, -44: 94.0, -43: 81.0, -42: 74.0, -41: 59.0, -40: 58.0, -39: 58.0, -38: 22.0, -37: 26.0, -36: 29.0, -35: 29.0, -34: 100.0, -33: 13.0, -32: 7.0, -31: 11.0, -30: 15.0, -29: 13.0, -28: 5.0, -27: 12.0, -26: 9.0, -25: 9.0, -24: 3.0, -23: 11.0, -22: 11.0, -21: 6.0, -20: 41.0, -19: 4.0, -18: 5.0, -17: 7.0, -16: 8.0, -15: 3.0, -14: 19.0, -13: 3.0, -12: 1.0, -11: 11.0, -10: 1.0, -9: 2.0, -8: 0.0, -7: 2.0, -6: 1.0, -5: 1.0, -4: 0.0, -3: 0.0, }}, min_key:-383, max_key:-5, offset:-386, negative_store: {}}, min_key:0, max_key:0, offset:0, zero_count: 4879.0, count: 145401.0, sum: 17311.247021079354, min: 0.0, max: 0.9029300212860107


store #2 
store: {-383: 1.0, -382: 0.0, -381: 0.0, -380: 0.0, -379: 0.0, -378: 0.0, -377: 0.0, -376: 0.0, -375: 0.0, -374: 0.0, -373: 0.0, -372: 0.0, -371: 0.0, -370: 0.0, -369: 0.0, -368: 0.0, -367: 0.0, -366: 0.0, -365: 0.0, -364: 0.0, -363: 0.0, -362: 0.0, -361: 0.0, -360: 0.0, -359: 0.0, -358: 0.0, -357: 0.0, -356: 0.0, -355: 0.0, -354: 0.0, -353: 0.0, -352: 0.0, -351: 0.0, -350: 1.0, -349: 0.0, -348: 0.0, -347: 0.0, -346: 0.0, -345: 0.0, -344: 0.0, -343: 0.0, -342: 1.0, -341: 0.0, -340: 0.0, -339: 0.0, -338: 0.0, -337: 0.0, -336: 0.0, -335: 0.0, -334: 0.0, -333: 1.0, -332: 0.0, -331: 0.0, -330: 0.0, -329: 0.0, -328: 0.0, -327: 0.0, -326: 0.0, -325: 0.0, -324: 0.0, -323: 0.0, -322: 0.0, -321: 0.0, -320: 0.0, -319: 1.0, -318: 0.0, -317: 0.0, -316: 1.0, -315: 0.0, -314: 0.0, -313: 0.0, -312: 0.0, -311: 0.0, -310: 0.0, -309: 0.0, -308: 0.0, -307: 0.0, -306: 0.0, -305: 3.0, -304: 1.0, -303: 1.0, -302: 0.0, -301: 0.0, -300: 1.0, -299: 0.0, -298: 0.0, -297: 0.0, -296: 0.0, -295: 0.0, -294: 1.0, -293: 1.0, -292: 0.0, -291: 1.0, -290: 1.0, -289: 0.0, -288: 0.0, -287: 0.0, -286: 0.0, -285: 3.0, -284: 1.0, -283: 3.0, -282: 1.0, -281: 1.0, -280: 1.0, -279: 2.0, -278: 0.0, -277: 3.0, -276: 3.0, -275: 1.0, -274: 3.0, -273: 1.0, -272: 1.0, -271: 5.0, -270: 6.0, -269: 1.0, -268: 2.0, -267: 1.0, -266: 4.0, -265: 3.0, -264: 1.0, -263: 2.0, -262: 2.0, -261: 2.0, -260: 1.0, -259: 5.0, -258: 4.0, -257: 1.0, -256: 6.0, -255: 3.0, -254: 4.0, -253: 5.0, -252: 7.0, -251: 5.0, -250: 4.0, -249: 4.0, -248: 3.0, -247: 8.0, -246: 8.0, -245: 4.0, -244: 6.0, -243: 3.0, -242: 5.0, -241: 5.0, -240: 6.0, -239: 11.0, -238: 2.0, -237: 13.0, -236: 8.0, -235: 9.0, -234: 9.0, -233: 10.0, -232: 5.0, -231: 6.0, -230: 10.0, -229: 9.0, -228: 5.0, -227: 14.0, -226: 14.0, -225: 12.0, -224: 13.0, -223: 11.0, -222: 17.0, -221: 8.0, -220: 10.0, -219: 8.0, -218: 15.0, -217: 19.0, -216: 12.0, -215: 10.0, -214: 20.0, -213: 27.0, -212: 17.0, -211: 14.0, -210: 21.0, -209: 21.0, -208: 19.0, -207: 18.0, -206: 24.0, -205: 29.0, -204: 23.0, -203: 41.0, -202: 31.0, -201: 29.0, -200: 21.0, -199: 32.0, -198: 40.0, -197: 31.0, -196: 32.0, -195: 46.0, -194: 29.0, -193: 48.0, -192: 49.0, -191: 47.0, -190: 50.0, -189: 43.0, -188: 56.0, -187: 41.0, -186: 51.0, -185: 46.0, -184: 50.0, -183: 65.0, -182: 54.0, -181: 54.0, -180: 68.0, -179: 66.0, -178: 72.0, -177: 62.0, -176: 71.0, -175: 91.0, -174: 67.0, -173: 69.0, -172: 71.0, -171: 77.0, -170: 103.0, -169: 85.0, -168: 85.0, -167: 96.0, -166: 103.0, -165: 82.0, -164: 102.0, -163: 107.0, -162: 120.0, -161: 96.0, -160: 112.0, -159: 121.0, -158: 133.0, -157: 118.0, -156: 123.0, -155: 116.0, -154: 147.0, -153: 161.0, -152: 177.0, -151: 147.0, -150: 156.0, -149: 168.0, -148: 161.0, -147: 157.0, -146: 175.0, -145: 166.0, -144: 176.0, -143: 164.0, -142: 161.0, -141: 201.0, -140: 190.0, -139: 213.0, -138: 221.0, -137: 254.0, -136: 226.0, -135: 249.0, -134: 205.0, -133: 236.0, -132: 241.0, -131: 268.0, -130: 261.0, -129: 241.0, -128: 268.0, -127: 250.0, -126: 274.0, -125: 270.0, -124: 293.0, -123: 273.0, -122: 320.0, -121: 309.0, -120: 269.0, -119: 305.0, -118: 292.0, -117: 286.0, -116: 310.0, -115: 319.0, -114: 310.0, -113: 325.0, -112: 368.0, -111: 365.0, -110: 323.0, -109: 368.0, -108: 334.0, -107: 338.0, -106: 354.0, -105: 367.0, -104: 302.0, -103: 404.0, -102: 349.0, -101: 360.0, -100: 349.0, -99: 327.0, -98: 320.0, -97: 367.0, -96: 318.0, -95: 338.0, -94: 316.0, -93: 348.0, -92: 304.0, -91: 276.0, -90: 313.0, -89: 364.0, -88: 275.0, -87: 266.0, -86: 267.0, -85: 270.0, -84: 255.0, -83: 246.0, -82: 243.0, -81: 255.0, -80: 266.0, -79: 237.0, -78: 227.0, -77: 220.0, -76: 218.0, -75: 208.0, -74: 190.0, -73: 193.0, -72: 152.0, -71: 172.0, -70: 171.0, -69: 187.0, -68: 144.0, -67: 130.0, -66: 123.0, -65: 122.0, -64: 111.0, -63: 97.0, -62: 78.0, -61: 94.0, -60: 85.0, -59: 67.0, -58: 72.0, -57: 58.0, -56: 44.0, -55: 36.0, -54: 67.0, -53: 45.0, -52: 41.0, -51: 40.0, -50: 31.0, -49: 31.0, -48: 15.0, -47: 21.0, -46: 17.0, -45: 33.0, -44: 20.0, -43: 10.0, -42: 11.0, -41: 10.0, -40: 12.0, -39: 11.0, -38: 4.0, -37: 6.0, -36: 4.0, -35: 6.0, -34: 19.0, -33: 3.0, -32: 2.0, -31: 2.0, -30: 7.0, -29: 1.0, -28: 0.0, -27: 3.0, -26: 1.0, -25: 2.0, -24: 0.0, -23: 1.0, -22: 0.0, -21: 0.0, -20: 9.0, -19: 0.0, -18: 2.0, -17: 1.0, -16: 2.0, -15: 0.0, -14: 1.0, -13: 0.0, -12: 1.0, -11: 3.0, -10: 0.0, -9: 0.0, -8: 0.0, -7: 0.0, -6: 0.0, -5: 0.0, -4: 0.0, -3: 0.0, -2: 0.0, -1: 0.0, 0: 1.0, }}, min_key:-383, max_key:0, offset:-383, negative_store: {}}, min_key:0, max_key:0, offset:0, zero_count: 974.0, count: 29277.0, sum: 3412.2428776764136, min: 0.0, max: 1.0

**Comment by Kyle-Verhoog** [comment]
@hay86 [ddsketch 2.0.4 has been released](https://pypi.org/project/ddsketch/2.0.4/) with the fix. Let me know if there are any issues!
