### ISSUE TITLE
CDF function

### ISSUE THREAD

**Issue by MaxHalford** [DataDog/sketches-py#8]
Hello, this is not so much an issue but a request. I've recently started evaluating different algorithms for estimating cumulative distribution functions (CDFs) [here](https://github.com/MaxHalford/streaming-cdf-benchmark). I would love to add your method to the benchmark, but I'm not sure how to proceed in order to add a CDF function. Is this something that would be easy or not? In most cases, having approximate quantiles means that we can also access an approximate CDF because both are inversely related. 

Kind regards, and great work.

**Comment by githomin** [comment]
Hello, and apologies for the extremely late response. It seems that relative-error quantile sketches are a poor fit for estimating CDFs. For instance if an empirical distribution is tightly concentrated around a point, then a relative-error quantile sketch could put all the values of the values into a single bucket, and the CDF function would always return 0 or 1. A quantile sketch with rank error guarantees are more appropriate for this use-case.
